# Application settings
app.author = Wayne Chung Enterprises
app.class = quest.Questcraft
app.color = 255, 255, 255
app.description = An application for questing and crafting.
app.gui = app.controller.JavaFXApplication
app.splash = quest.view.SplashScreen